services:
    # pie (ports: 810x)
    pie-tdn-1400-1600:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-1400-1600:${VERSION}
        build:
            context: pie/TDN-1400-1600
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8100:8080

    pie-tdn-1600-1900:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-1600-1900:${VERSION}
        build:
            context: pie/TDN-1600-1900
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8101:8080

    pie-tdn-all:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-all:${VERSION}
        build:
            context: pie/TDN-ALL
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8102:8080

    pie-tdn-bab:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-bab:${VERSION}
        build:
            context: pie/TDN-BAB
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8103:8080

    pie-tdn-clvn:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-clvn:${VERSION}
        build:
            context: pie/TDN-CLVN
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8104:8080

    pie-tdn-cour:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-cour:${VERSION}
        build:
            context: pie/TDN-COUR
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8105:8080

    pie-tdn-dbnldq:
        image: instituutnederlandsetaal/taggers-dockerized-pie-tdn-dbnldq:${VERSION}
        build:
            context: pie/TDN-DBNLDQ
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8106:8080

    # huggingface (port: 811x)
    hug-tdn-1400-1600:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-1400-1600:${VERSION}
        build:
            context: huggingface/TDN-1400-1600
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8110:8080

    hug-tdn-1600-1900:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-1600-1900:${VERSION}
        build:
            context: huggingface/TDN-1600-1900
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8111:8080

    hug-tdn-all:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-all:${VERSION}
        build:
            context: huggingface/TDN-ALL
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8112:8080

    hug-tdn-bab:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-bab:${VERSION}
        build:
            context: huggingface/TDN-BAB
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8113:8080

    hug-tdn-clvn:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-clvn:${VERSION}
        build:
            context: huggingface/TDN-CLVN
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8114:8080

    hug-tdn-cour:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-cour:${VERSION}
        build:
            context: huggingface/TDN-COUR
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8115:8080

    hug-tdn-dbnldq:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-dbnldq:${VERSION}
        build:
            context: huggingface/TDN-DBNLDQ
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8116:8080

    hug-tdn-all-enhanced:
        image: instituutnederlandsetaal/taggers-dockerized-hug-tdn-all-enhanced:${VERSION}
        build:
            context: huggingface/TDN-ALL-ENHANCED
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8117:8080

    # ud-parsers (812X)
    spacy-gpu:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - USE_GPU=1
            - NUM_WORKERS=6
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8120:8080 # cpu & gpu share port: choose one
        deploy:
            resources:
                limits:
                    memory: 24G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

    spacy-cpu:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8120:8080 # cpu & gpu share port: choose one

    stanza-alpino-conll02:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_MODEL=alpino
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8121:8080

    stanza-lassysmall-wikiner:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_MODEL=lassysmall
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8122:8080

    flair-cpu:
        image: instituutnederlandsetaal/taggers-dockerized-flair:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8123:8080

    flair-gpu:
        image: instituutnederlandsetaal/taggers-dockerized-flair:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8123:8080
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

networks:
    default:
        name: taggers-network
        driver: bridge # external applications can attach to this network to access the taggers 
