services:
    # ud-parsers (812X)
    spacy-gpu:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - USE_GPU=1
            - NUM_WORKERS=6
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8120:8080 # cpu & gpu share port: choose one
        deploy:
            resources:
                limits:
                    memory: 24G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

    spacy-cpu:
        image: instituutnederlandsetaal/taggers-dockerized-spacy:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8120:8080 # cpu & gpu share port: choose one

    stanza-alpino-conll02:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_MODEL=alpino
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8121:8080

    stanza-lassysmall-wikiner:
        image: instituutnederlandsetaal/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_MODEL=lassysmall
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8122:8080

    flair-cpu:
        image: instituutnederlandsetaal/taggers-dockerized-flair:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8123:8080

    flair-gpu:
        image: instituutnederlandsetaal/taggers-dockerized-flair:${VERSION}
        restart: unless-stopped
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8123:8080
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

networks:
    default:
        name: taggers-network
        driver: bridge # external applications can attach to this network to access the taggers 
