services:
    # spacy (ports: 812x)
    spacy-nl-lg:
        image: ccl-kuleuven/taggers-dockerized-spacy-nl-lg:1
        build:
            context: spacy/base
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=nl_core_news_lg
        restart: unless-stopped
        ports:
            - 8120:8080

    spacy-en-lg:
        image: ccl-kuleuven/taggers-dockerized-spacy-en-lg:1
        build:
            context: spacy/base
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=en_core_web_lg
        restart: unless-stopped
        ports:
            - 8121:8080

    spacy-fr-lg:
        image: ccl-kuleuven/taggers-dockerized-spacy-fr-lg:1
        build:
            context: spacy/base
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=fr_core_news_lg
        restart: unless-stopped
        ports:
            - 8122:8080

    spacy-de-lg:
        image: ccl-kuleuven/taggers-dockerized-spacy-de-lg:1
        build:
            context: spacy/base
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=de_core_news_lg
        restart: unless-stopped
        ports:
            - 8123:8080
    # LeTs (ports: 813x)
    lets-nl:
        image: instituutnederlandsetaal/taggers-dockerized-lets-nl:dev
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=nl
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8130:8080
    lets-fr:
        image: instituutnederlandsetaal/taggers-dockerized-lets-fr:dev
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=fr
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8131:8080
    lets-de:
        image: instituutnederlandsetaal/taggers-dockerized-lets-de:dev
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=de
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8132:8080
    lets-en:
        image: instituutnederlandsetaal/taggers-dockerized-lets-en:dev
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=en
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8133:8080

networks:
    taggers-network:
        # external applications can attach to this network to access the taggers 
        driver: bridge
