# coding: utf-8
# !! AUTO-GENERATED by ut_generator.py on 2016-12-13 13:48:13 !!
# !! DO NOT EDIT - YOUR CHANGES MAY BE OVERWRITTEN !!

import unittest

import ner_steps.feat_vect as feat_vect
from ner_steps.feat_vect import ScannedTokenNER

class TestScannedTokenNER(unittest.TestCase):

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.first_capital

    def test_ScannedTokenNER_first_capital_case_1(self):
        self.assertTrue(ScannedTokenNER("Aceui.").first_capital)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_first_capital_case_2(self):
        self.assertTrue(ScannedTokenNER("Àçèüî.").first_capital)

    def test_ScannedTokenNER_first_capital_case_3(self):
        self.assertFalse(ScannedTokenNER("aCEUI").first_capital)

    def test_ScannedTokenNER_first_capital_case_4(self):
        self.assertFalse(ScannedTokenNER("âÇÉÛÏ").first_capital)

    def test_ScannedTokenNER_first_capital_case_5(self):
        self.assertFalse(ScannedTokenNER(".").first_capital)

    def test_ScannedTokenNER_first_capital_case_6(self):
        self.assertFalse(ScannedTokenNER(".ACEUI").first_capital)

    def test_ScannedTokenNER_first_capital_case_7(self):
        self.assertFalse(ScannedTokenNER(".ÄÇÉÛÏ").first_capital)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.all_capitals

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_1(self):
        self.assertTrue(ScannedTokenNER("ACEUI").all_capitals)

    @unittest.skip('no special letters handling yet|Java version incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_2(self):
        self.assertTrue(ScannedTokenNER("ÄÇÉÛÏ").all_capitals)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_3(self):
        self.assertFalse(ScannedTokenNER("ACEUI2").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_4(self):
        self.assertFalse(ScannedTokenNER("ÄÇÉÛÏ2").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_5(self):
        self.assertFalse(ScannedTokenNER("ACEUI,").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_6(self):
        self.assertFalse(ScannedTokenNER("ÄÇÉÛÏ,").all_capitals)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_7(self):
        self.assertFalse(ScannedTokenNER(".").all_capitals)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_8(self):
        self.assertFalse(ScannedTokenNER("").all_capitals)

    def test_ScannedTokenNER_all_capitals_case_9(self):
        self.assertFalse(ScannedTokenNER("ACEUb").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_10(self):
        self.assertFalse(ScannedTokenNER("ÄÇÉÛî").all_capitals)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_11(self):
        self.assertFalse(ScannedTokenNER("iACEU").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_12(self):
        self.assertFalse(ScannedTokenNER("îÄÇÉÛ").all_capitals)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_all_capitals_case_13(self):
        self.assertFalse(ScannedTokenNER("aceui").all_capitals)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_capitals_case_14(self):
        self.assertFalse(ScannedTokenNER("àçèüî").all_capitals)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.internal_caps

    def test_ScannedTokenNER_internal_caps_case_1(self):
        self.assertTrue(ScannedTokenNER("ACEUI").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_2(self):
        self.assertTrue(ScannedTokenNER("ÄÇÉÛÏ").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_3(self):
        self.assertTrue(ScannedTokenNER("aCEUI").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_4(self):
        self.assertTrue(ScannedTokenNER("äÇÉÛÏ").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_5(self):
        self.assertTrue(ScannedTokenNER("AcEuio").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_6(self):
        self.assertTrue(ScannedTokenNER("ÄçÈùïö").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_7(self):
        self.assertTrue(ScannedTokenNER("aceuI").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_8(self):
        self.assertTrue(ScannedTokenNER("àçèüÎ").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_9(self):
        self.assertTrue(ScannedTokenNER("aC").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_10(self):
        self.assertTrue(ScannedTokenNER("àÇ").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_11(self):
        self.assertFalse(ScannedTokenNER("A").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_12(self):
        self.assertFalse(ScannedTokenNER("Ä").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_13(self):
        self.assertTrue(ScannedTokenNER("AceuI").internal_caps)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_internal_caps_case_14(self):
        self.assertTrue(ScannedTokenNER("ÄçèüÎ").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_15(self):
        self.assertFalse(ScannedTokenNER("Aceui").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_16(self):
        self.assertFalse(ScannedTokenNER("Äçèüî").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_17(self):
        self.assertFalse(ScannedTokenNER("aceuio").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_18(self):
        self.assertFalse(ScannedTokenNER("àçèüîö").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_19(self):
        self.assertFalse(ScannedTokenNER("Aceuio").internal_caps)

    def test_ScannedTokenNER_internal_caps_case_20(self):
        self.assertFalse(ScannedTokenNER("Äçèùïö").internal_caps)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.all_lower_case

    def test_ScannedTokenNER_all_lower_case_case_1(self):
        self.assertTrue(ScannedTokenNER("aceuio").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_2(self):
        self.assertTrue(ScannedTokenNER("àçèüîö").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_3(self):
        self.assertTrue(ScannedTokenNER("ace_uio").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_4(self):
        self.assertTrue(ScannedTokenNER("àçè_üîö").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_5(self):
        self.assertTrue(ScannedTokenNER("aceuio.").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_6(self):
        self.assertTrue(ScannedTokenNER("àçèüîö.").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_7(self):
        self.assertFalse(ScannedTokenNER("aceuiO").all_lower_case)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_lower_case_case_8(self):
        self.assertFalse(ScannedTokenNER("àçèüîÖ").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_9(self):
        self.assertFalse(ScannedTokenNER("Aceuio").all_lower_case)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_lower_case_case_10(self):
        self.assertFalse(ScannedTokenNER("Äçèüîö").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_11(self):
        self.assertFalse(ScannedTokenNER("abCDef").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_12(self):
        self.assertFalse(ScannedTokenNER("acEUio").all_lower_case)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_lower_case_case_13(self):
        self.assertFalse(ScannedTokenNER("àçËÙîö").all_lower_case)

    def test_ScannedTokenNER_all_lower_case_case_14(self):
        self.assertFalse(ScannedTokenNER("ACEUI").all_lower_case)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_all_lower_case_case_15(self):
        self.assertFalse(ScannedTokenNER("ÄÇÉÛÏ").all_lower_case)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.contains_digit

    def test_ScannedTokenNER_contains_digit_case_1(self):
        self.assertTrue(ScannedTokenNER("Ab.,'c228def").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_2(self):
        self.assertTrue(ScannedTokenNER("Äß.,'ç228üîö").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_3(self):
        self.assertTrue(ScannedTokenNER("1").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_4(self):
        self.assertTrue(ScannedTokenNER("Ab.,'Cde9").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_5(self):
        self.assertTrue(ScannedTokenNER("Äß.,'Çüî9").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_6(self):
        self.assertTrue(ScannedTokenNER("5def").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_7(self):
        self.assertTrue(ScannedTokenNER("5üîö").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_8(self):
        self.assertFalse(ScannedTokenNER("IOAE").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_9(self):
        self.assertFalse(ScannedTokenNER("ÏÔÄÉ").contains_digit)

    def test_ScannedTokenNER_contains_digit_case_10(self):
        self.assertFalse(ScannedTokenNER("m³").contains_digit)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.contains_digit_and_alpha

    def test_ScannedTokenNER_contains_digit_and_alpha_case_1(self):
        self.assertTrue(ScannedTokenNER("1234A").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_2(self):
        self.assertTrue(ScannedTokenNER("1234Ä").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_3(self):
        self.assertTrue(ScannedTokenNER("1U").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_4(self):
        self.assertTrue(ScannedTokenNER("1Ü").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_5(self):
        self.assertTrue(ScannedTokenNER("Ab789").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_6(self):
        self.assertTrue(ScannedTokenNER("Äß789").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_7(self):
        self.assertTrue(ScannedTokenNER("5def").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_8(self):
        self.assertTrue(ScannedTokenNER("5üîö").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_9(self):
        self.assertFalse(ScannedTokenNER("IOAE").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_10(self):
        self.assertFalse(ScannedTokenNER("ÏÔÄÉ").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_11(self):
        self.assertFalse(ScannedTokenNER("456789").contains_digit_and_alpha)

    def test_ScannedTokenNER_contains_digit_and_alpha_case_12(self):
        self.assertFalse(ScannedTokenNER("m³").contains_digit_and_alpha)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.only_digits

    def test_ScannedTokenNER_only_digits_case_1(self):
        self.assertFalse(ScannedTokenNER("40,000").only_digits)

    def test_ScannedTokenNER_only_digits_case_2(self):
        self.assertTrue(ScannedTokenNER("1234").only_digits)

    def test_ScannedTokenNER_only_digits_case_3(self):
        self.assertTrue(ScannedTokenNER("100").only_digits)

    def test_ScannedTokenNER_only_digits_case_4(self):
        self.assertFalse(ScannedTokenNER("A789").only_digits)

    def test_ScannedTokenNER_only_digits_case_5(self):
        self.assertFalse(ScannedTokenNER("Â789").only_digits)

    def test_ScannedTokenNER_only_digits_case_6(self):
        self.assertFalse(ScannedTokenNER("5def").only_digits)

    def test_ScannedTokenNER_only_digits_case_7(self):
        self.assertFalse(ScannedTokenNER("5üîö").only_digits)

    @unittest.skip('wrong expected value')
    def test_ScannedTokenNER_only_digits_case_8(self):
        self.assertTrue(ScannedTokenNER("").only_digits)

    def test_ScannedTokenNER_only_digits_case_9(self):
        self.assertFalse(ScannedTokenNER("IOAE").only_digits)

    def test_ScannedTokenNER_only_digits_case_10(self):
        self.assertFalse(ScannedTokenNER("ÏÔÄÉ").only_digits)

    def test_ScannedTokenNER_only_digits_case_11(self):
        self.assertFalse(ScannedTokenNER("5678v").only_digits)

    def test_ScannedTokenNER_only_digits_case_12(self):
        self.assertFalse(ScannedTokenNER("5678ÿ").only_digits)

    def test_ScannedTokenNER_only_digits_case_13(self):
        self.assertFalse(ScannedTokenNER("⁰¹²³⁴⁵⁶⁷⁸⁹₀₁₂₃₄₅₆₇₈₉").only_digits)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.is_punctuation

    def test_ScannedTokenNER_is_punctuation_case_1(self):
        self.assertTrue(ScannedTokenNER("^").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_2(self):
        self.assertTrue(ScannedTokenNER(";").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_3(self):
        self.assertFalse(ScannedTokenNER("123,").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_4(self):
        self.assertFalse(ScannedTokenNER("!100").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_5(self):
        self.assertFalse(ScannedTokenNER("A789").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_6(self):
        self.assertFalse(ScannedTokenNER("Ä789").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_7(self):
        self.assertFalse(ScannedTokenNER("789").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_8(self):
        self.assertFalse(ScannedTokenNER("5def").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_9(self):
        self.assertFalse(ScannedTokenNER("5üîö").is_punctuation)

    @unittest.skip('wrong expected value')
    def test_ScannedTokenNER_is_punctuation_case_10(self):
        self.assertTrue(ScannedTokenNER("").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_11(self):
        self.assertTrue(ScannedTokenNER(",").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_12(self):
        self.assertTrue(ScannedTokenNER("!,./?").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_13(self):
        self.assertFalse(ScannedTokenNER("IOAE").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_14(self):
        self.assertFalse(ScannedTokenNER("ÏÔÄÉ").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_15(self):
        self.assertFalse(ScannedTokenNER("5678v").is_punctuation)

    def test_ScannedTokenNER_is_punctuation_case_16(self):
        self.assertFalse(ScannedTokenNER("5678ÿ").is_punctuation)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.contains_punctuation

    def test_ScannedTokenNER_contains_punctuation_case_1(self):
        self.assertFalse(ScannedTokenNER("^pas").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_2(self):
        self.assertTrue(ScannedTokenNER(";").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_3(self):
        self.assertFalse(ScannedTokenNER("Río").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_4(self):
        self.assertFalse(ScannedTokenNER("]").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_5(self):
        self.assertTrue(ScannedTokenNER("123,").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_6(self):
        self.assertTrue(ScannedTokenNER("!100").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_7(self):
        self.assertFalse(ScannedTokenNER("A789").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_8(self):
        self.assertFalse(ScannedTokenNER("Â789").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_9(self):
        self.assertFalse(ScannedTokenNER("5def").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_10(self):
        self.assertFalse(ScannedTokenNER("5üîö").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_11(self):
        self.assertTrue(ScannedTokenNER(",").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_12(self):
        self.assertTrue(ScannedTokenNER("EU,./42").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_13(self):
        self.assertTrue(ScannedTokenNER("ÈÜ,./42").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_14(self):
        self.assertFalse(ScannedTokenNER("IOAE").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_15(self):
        self.assertFalse(ScannedTokenNER("ÏÔÄÉ").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_16(self):
        self.assertFalse(ScannedTokenNER("5678v").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_17(self):
        self.assertFalse(ScannedTokenNER("5678ÿ").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_18(self):
        self.assertTrue(ScannedTokenNER("ACEUIO.").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_19(self):
        self.assertTrue(ScannedTokenNER("ÀÇÈÜÎÖ.").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_20(self):
        self.assertFalse(ScannedTokenNER("ACEUIO").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_21(self):
        self.assertFalse(ScannedTokenNER("ÀÇÈÜÎÖ").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_22(self):
        self.assertFalse(ScannedTokenNER("ACE%$@#_").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_23(self):
        self.assertFalse(ScannedTokenNER("ÀÇÈ%$@#_").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_24(self):
        self.assertTrue(ScannedTokenNER(".ACE%$@#").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_25(self):
        self.assertTrue(ScannedTokenNER(".ÀÇÈ%$@#").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_26(self):
        self.assertFalse(ScannedTokenNER("acE%$@#").contains_punctuation)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_contains_punctuation_case_27(self):
        self.assertFalse(ScannedTokenNER("àçÈ%$@#").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_28(self):
        self.assertTrue(ScannedTokenNER("ACE?$@#_").contains_punctuation)

    def test_ScannedTokenNER_contains_punctuation_case_29(self):
        self.assertTrue(ScannedTokenNER("ÀÇÈ?$@#_").contains_punctuation)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.is_hyphenated

    def test_ScannedTokenNER_is_hyphenated_case_1(self):
        self.assertFalse(ScannedTokenNER("12").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_2(self):
        self.assertFalse(ScannedTokenNER("-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_3(self):
        self.assertFalse(ScannedTokenNER("--").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_4(self):
        self.assertFalse(ScannedTokenNER("a-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_5(self):
        self.assertFalse(ScannedTokenNER("ä-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_6(self):
        self.assertFalse(ScannedTokenNER("A-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_7(self):
        self.assertFalse(ScannedTokenNER("À-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_8(self):
        self.assertFalse(ScannedTokenNER("ace-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_9(self):
        self.assertFalse(ScannedTokenNER("ACE-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_10(self):
        self.assertFalse(ScannedTokenNER("äçë-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_11(self):
        self.assertFalse(ScannedTokenNER("-ace?").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_12(self):
        self.assertFalse(ScannedTokenNER("-àçê?").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_13(self):
        self.assertFalse(ScannedTokenNER("-a-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_14(self):
        self.assertFalse(ScannedTokenNER("-â-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_15(self):
        self.assertFalse(ScannedTokenNER("-ace-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_16(self):
        self.assertFalse(ScannedTokenNER("-àçé-").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_17(self):
        self.assertTrue(ScannedTokenNER("12-a").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_18(self):
        self.assertTrue(ScannedTokenNER("12-ä").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_19(self):
        self.assertTrue(ScannedTokenNER("qwe-rt").is_hyphenated)

    def test_ScannedTokenNER_is_hyphenated_case_20(self):
        self.assertTrue(ScannedTokenNER("äßç-üä").is_hyphenated)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.is_initial

    def test_ScannedTokenNER_is_initial_case_1(self):
        self.assertTrue(ScannedTokenNER("A.").is_initial)

    def test_ScannedTokenNER_is_initial_case_2(self):
        self.assertFalse(ScannedTokenNER("A").is_initial)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_is_initial_case_3(self):
        self.assertFalse(ScannedTokenNER(".A").is_initial)

    @unittest.skip('incorrectly implemented')
    def test_ScannedTokenNER_is_initial_case_4(self):
        self.assertFalse(ScannedTokenNER("..A").is_initial)

    def test_ScannedTokenNER_is_initial_case_5(self):
        self.assertFalse(ScannedTokenNER("abc").is_initial)

    def test_ScannedTokenNER_is_initial_case_6(self):
        self.assertTrue(ScannedTokenNER("G.M.").is_initial)

    def test_ScannedTokenNER_is_initial_case_7(self):
        self.assertTrue(ScannedTokenNER("I.B.M.").is_initial)

    def test_ScannedTokenNER_is_initial_case_8(self):
        self.assertFalse(ScannedTokenNER("IBM").is_initial)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_is_initial_case_9(self):
        self.assertTrue(ScannedTokenNER("Â.").is_initial)

    def test_ScannedTokenNER_is_initial_case_10(self):
        self.assertFalse(ScannedTokenNER(".À").is_initial)

    def test_ScannedTokenNER_is_initial_case_11(self):
        self.assertFalse(ScannedTokenNER("..Ä").is_initial)

    def test_ScannedTokenNER_is_initial_case_12(self):
        self.assertFalse(ScannedTokenNER("àçé").is_initial)

    def test_ScannedTokenNER_is_initial_case_13(self):
        self.assertTrue(ScannedTokenNER("U.E.").is_initial)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_is_initial_case_14(self):
        self.assertTrue(ScannedTokenNER("Ù.Ë.").is_initial)

    def test_ScannedTokenNER_is_initial_case_15(self):
        self.assertTrue(ScannedTokenNER("U.S.A.").is_initial)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_is_initial_case_16(self):
        self.assertTrue(ScannedTokenNER("Ü.Ç.Â.").is_initial)

    def test_ScannedTokenNER_is_initial_case_17(self):
        self.assertFalse(ScannedTokenNER("IBM").is_initial)

    def test_ScannedTokenNER_is_initial_case_18(self):
        self.assertFalse(ScannedTokenNER("ÎÇÊ").is_initial)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.is_url

    def test_ScannedTokenNER_is_url_case_1(self):
        self.assertFalse(ScannedTokenNER("not-a-URL").is_url)

    def test_ScannedTokenNER_is_url_case_2(self):
        self.assertTrue(ScannedTokenNER("http://example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_3(self):
        self.assertTrue(ScannedTokenNER("https://example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_4(self):
        self.assertTrue(ScannedTokenNER("ftp://ftp.example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_5(self):
        self.assertTrue(ScannedTokenNER("mailto://someone@example.com").is_url)

    def test_ScannedTokenNER_is_url_case_6(self):
        self.assertTrue(ScannedTokenNER("www.example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_7(self):
        self.assertFalse(ScannedTokenNER("foooohttp://example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_8(self):
        self.assertFalse(ScannedTokenNER("barrrwww.example.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_9(self):
        self.assertFalse(ScannedTokenNER("wwwexample.com").is_url)

    @unittest.skip('incorrect java implementation')
    def test_ScannedTokenNER_is_url_case_10(self):
        self.assertFalse(ScannedTokenNER("http////::::example.com").is_url)

    def test_ScannedTokenNER_is_url_case_11(self):
        self.assertFalse(ScannedTokenNER("https/example.com").is_url)

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.prefix()

    def test_ScannedTokenNER_prefix_case_1(self):
        self.assertEqual("123", ScannedTokenNER("123").prefix(3))

    def test_ScannedTokenNER_prefix_case_2(self):
        self.assertEqual("123", ScannedTokenNER("1234").prefix(3))

    def test_ScannedTokenNER_prefix_case_3(self):
        self.assertEqual("123", ScannedTokenNER("12345").prefix(3))

    def test_ScannedTokenNER_prefix_case_4(self):
        self.assertEqual("123", ScannedTokenNER("123").prefix(4))

    def test_ScannedTokenNER_prefix_case_5(self):
        self.assertTrue(ScannedTokenNER("1").prefix(4))

    def test_ScannedTokenNER_prefix_case_6(self):
        self.assertTrue(ScannedTokenNER("123").prefix(1))

    def test_ScannedTokenNER_prefix_case_7(self):
        self.assertEqual("", ScannedTokenNER("123").prefix(0))

    def test_ScannedTokenNER_prefix_case_8(self):
        self.assertEqual("abc", ScannedTokenNER("abc").prefix(3))

    def test_ScannedTokenNER_prefix_case_9(self):
        self.assertEqual("abc", ScannedTokenNER("abc4").prefix(3))

    def test_ScannedTokenNER_prefix_case_10(self):
        self.assertEqual("abc", ScannedTokenNER("abc45").prefix(3))

    def test_ScannedTokenNER_prefix_case_11(self):
        self.assertEqual("abc", ScannedTokenNER("abc").prefix(4))

    def test_ScannedTokenNER_prefix_case_12(self):
        self.assertEqual("a", ScannedTokenNER("a").prefix(4))

    def test_ScannedTokenNER_prefix_case_13(self):
        self.assertEqual("a", ScannedTokenNER("abc").prefix(1))

    def test_ScannedTokenNER_prefix_case_14(self):
        self.assertEqual("", ScannedTokenNER("abc").prefix(0))

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.suffix()

    def test_ScannedTokenNER_suffix_case_1(self):
        self.assertEqual("123", ScannedTokenNER("123").suffix(3))

    def test_ScannedTokenNER_suffix_case_2(self):
        self.assertEqual("234", ScannedTokenNER("1234").suffix(3))

    def test_ScannedTokenNER_suffix_case_3(self):
        self.assertEqual("345", ScannedTokenNER("12345").suffix(3))

    def test_ScannedTokenNER_suffix_case_4(self):
        self.assertEqual("123", ScannedTokenNER("123").suffix(4))

    def test_ScannedTokenNER_suffix_case_5(self):
        self.assertTrue(ScannedTokenNER("1").suffix(4))

    def test_ScannedTokenNER_suffix_case_6(self):
        self.assertEqual("3", ScannedTokenNER("123").suffix(1))

    def test_ScannedTokenNER_suffix_case_7(self):
        self.assertEqual("", ScannedTokenNER("123").suffix(0))

    def test_ScannedTokenNER_suffix_case_8(self):
        self.assertEqual("abc", ScannedTokenNER("abc").suffix(3))

    def test_ScannedTokenNER_suffix_case_9(self):
        self.assertEqual("bcd", ScannedTokenNER("abcd").suffix(3))

    def test_ScannedTokenNER_suffix_case_10(self):
        self.assertEqual("cde", ScannedTokenNER("abcde").suffix(3))

    def test_ScannedTokenNER_suffix_case_11(self):
        self.assertEqual("abc", ScannedTokenNER("abc").suffix(4))

    def test_ScannedTokenNER_suffix_case_12(self):
        self.assertEqual("a", ScannedTokenNER("a").suffix(4))

    def test_ScannedTokenNER_suffix_case_13(self):
        self.assertEqual("c", ScannedTokenNER("abc").suffix(1))

    def test_ScannedTokenNER_suffix_case_14(self):
        self.assertEqual("", ScannedTokenNER("abc").suffix(0))

    # ________________________________________________________________________
    # Test cases for function ScannedTokenNER.word_shape

    def test_ScannedTokenNER_word_shape_case_1(self):
        self.assertEqual("other", ScannedTokenNER("Historiek_").word_shape)

    def test_ScannedTokenNER_word_shape_case_2(self):
        self.assertEqual("other", ScannedTokenNER("MRI_IRM").word_shape)

    def test_ScannedTokenNER_word_shape_case_3(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("No-one").word_shape)

    def test_ScannedTokenNER_word_shape_case_4(self):
        self.assertEqual("allCapsAndPunct", ScannedTokenNER("CAPACITY-BUILDING").word_shape)

    def test_ScannedTokenNER_word_shape_case_5(self):
        self.assertEqual("allCapsAndPunct", ScannedTokenNER("MM]YYYY").word_shape)

    def test_ScannedTokenNER_word_shape_case_6(self):
        self.assertEqual("allCapsAndPunct", ScannedTokenNER("N=").word_shape)

    def test_ScannedTokenNER_word_shape_case_7(self):
        self.assertEqual("allLowercase", ScannedTokenNER("aceuio").word_shape)

    def test_ScannedTokenNER_word_shape_case_8(self):
        self.assertEqual("onlyDigits", ScannedTokenNER("Ô98").word_shape)

    def test_ScannedTokenNER_word_shape_case_9(self):
        self.assertEqual("onlyDigits", ScannedTokenNER("â€~03").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_10(self):
        self.assertEqual("allLowercase", ScannedTokenNER("àçèüîö").word_shape)

    def test_ScannedTokenNER_word_shape_case_11(self):
        self.assertEqual("onlyDigits", ScannedTokenNER("1234").word_shape)

    def test_ScannedTokenNER_word_shape_case_12(self):
        self.assertEqual("containsDigitAndAlpha", ScannedTokenNER("12aceACEe5u34").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_13(self):
        self.assertEqual("containsDigitAndAlpha", ScannedTokenNER("12àçèÄÇÉè5ü34").word_shape)

    def test_ScannedTokenNER_word_shape_case_14(self):
        self.assertEqual("onlyPunct", ScannedTokenNER("#$%^&-=+[]{}!@*()<>;:/|`~'").word_shape)

    def test_ScannedTokenNER_word_shape_case_15(self):
        self.assertEqual("other", ScannedTokenNER("_").word_shape)

    def test_ScannedTokenNER_word_shape_case_16(self):
        self.assertEqual("other", ScannedTokenNER("____").word_shape)

    def test_ScannedTokenNER_word_shape_case_17(self):
        self.assertEqual("allCaps", ScannedTokenNER("ACEUI").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_18(self):
        self.assertEqual("allCaps", ScannedTokenNER("ÄÇÉÛÏ").word_shape)

    def test_ScannedTokenNER_word_shape_case_19(self):
        self.assertEqual("mixedCase", ScannedTokenNER("ACeuI").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_20(self):
        self.assertEqual("mixedCase", ScannedTokenNER("ÄÇèüÏ").word_shape)

    def test_ScannedTokenNER_word_shape_case_21(self):
        self.assertEqual("allCapsAndPunct", ScannedTokenNER("AC,EU,I.,").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_22(self):
        self.assertEqual("allCapsAndPunct", ScannedTokenNER("ÄÇ,ÉÛ,Ï.").word_shape)

    def test_ScannedTokenNER_word_shape_case_23(self):
        self.assertEqual("capPeriod", ScannedTokenNER("A.").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_24(self):
        self.assertEqual("capPeriod", ScannedTokenNER("Ä.").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_25(self):
        self.assertEqual("mixedCase", ScannedTokenNER("acEUiACeuI").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_26(self):
        self.assertEqual("mixedCase", ScannedTokenNER("àçËÙîÄÇèüî").word_shape)

    def test_ScannedTokenNER_word_shape_case_27(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("ACEui,aceUI!ACEui.").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_28(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("ÄÇÉüî,àçËÙÏ!ÄÇèüî.").word_shape)

    def test_ScannedTokenNER_word_shape_case_29(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("AcEui,aceUI!ACEui.").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_30(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("ÄçÉüî,àçËÙÏ!ÄÇèüî.").word_shape)

    def test_ScannedTokenNER_word_shape_case_31(self):
        self.assertEqual("alphaAndPunct", ScannedTokenNER("aCEui,aceUI!ACEui.").word_shape)

    @unittest.skip('no special letters handling yet')
    def test_ScannedTokenNER_word_shape_case_32(self):
        self.assertEqual("alphaAndPunct", ScannedTokenNER("àÇÉüî,àçËÙÏ!ÄÇèüî.").word_shape)

    def test_ScannedTokenNER_word_shape_case_33(self):
        self.assertEqual("onlyPunct", ScannedTokenNER(".,!?.").word_shape)

    def test_ScannedTokenNER_word_shape_case_34(self):
        self.assertEqual("alphaAndPunct", ScannedTokenNER("m³").word_shape)

    def test_ScannedTokenNER_word_shape_case_35(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("Río").word_shape)

    def test_ScannedTokenNER_word_shape_case_36(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("Paraná").word_shape)

    def test_ScannedTokenNER_word_shape_case_37(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("Cristóbal").word_shape)

    def test_ScannedTokenNER_word_shape_case_38(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("Açu").word_shape)

    def test_ScannedTokenNER_word_shape_case_39(self):
        self.assertEqual("firstCapAlphaAndPunct", ScannedTokenNER("No-one").word_shape)

    def test_ScannedTokenNER_word_shape_case_40(self):
        self.assertEqual("alphaAndPunct", ScannedTokenNER("http://www.fedweb.belgium.be/nl/over_de_organisatie/ontwikkeling_en_ondersteuning/medewerkers/competentiemanagement/").word_shape)

    # ________________________________________________________________________
    # Test cases for function feat_vect.map_pos_ner()

    def test_feat_vect_map_pos_ner_case_1(self):
        self.assertEqual("SYM", feat_vect.map_pos_ner("ADJ", "en"))

    def test_feat_vect_map_pos_ner_case_2(self):
        self.assertEqual("(", feat_vect.map_pos_ner("(", "en"))

    def test_feat_vect_map_pos_ner_case_3(self):
        self.assertEqual("CC", feat_vect.map_pos_ner("CC", "en"))

    def test_feat_vect_map_pos_ner_case_4(self):
        self.assertEqual("NP", feat_vect.map_pos_ner("SPEC(deeleigen)", "nl"))

    def test_feat_vect_map_pos_ner_case_5(self):
        self.assertEqual("FW", feat_vect.map_pos_ner("SPEC(vreemd)", "nl"))

    def test_feat_vect_map_pos_ner_case_6(self):
        self.assertEqual("NP", feat_vect.map_pos_ner("N(eigen", "nl"))

    def test_feat_vect_map_pos_ner_case_7(self):
        self.assertEqual("SPEC", feat_vect.map_pos_ner("SPEC(fooo)", "nl"))

    @unittest.skip("Java fails with 'String index out of range: -1'")
    def test_feat_vect_map_pos_ner_case_8(self):
        self.assertEqual("SPEC", feat_vect.map_pos_ner("SPEC", "nl"))

    def test_feat_vect_map_pos_ner_case_9(self):
        self.assertEqual("A", feat_vect.map_pos_ner("ADJ", "fr"))

    def test_feat_vect_map_pos_ner_case_10(self):
        self.assertEqual("ADV", feat_vect.map_pos_ner("ADV", "fr"))

    def test_feat_vect_map_pos_ner_case_11(self):
        self.assertEqual("CHIF", feat_vect.map_pos_ner("NUM", "fr"))

    def test_feat_vect_map_pos_ner_case_12(self):
        self.assertEqual("P", feat_vect.map_pos_ner("PRP", "fr"))

    def test_feat_vect_map_pos_ner_case_13(self):
        self.assertEqual("PONCT", feat_vect.map_pos_ner("FRFOO", "fr"))

    def test_feat_vect_map_pos_ner_case_14(self):
        self.assertEqual("DEFOO", feat_vect.map_pos_ner("DEFOO", "de"))


if __name__ == '__main__':
    unittest.main()
