"""
package test.unittests.lt3_tools
Created on 2016/11/19.

Q&D generator for tests for the LT3 features-related functions.

Run this to regenerate Python and/or Java unit tests within the current directory.
Test cases defined by the meta-test-case data in test.unittests.l3t_tools.metacases.

Examples of usage:

Generate python test mosule using default output filename::

  $ python3 ut_generator.py -l python

Generate Java test class using stdout for output::
 
  $ python3 ut_generator.py -l java -o -

"""

import os
import sys
from datetime import datetime
from os.path import abspath, normpath, dirname, join as pjoin

REPO_ROOT = normpath(abspath(pjoin(dirname(__file__), "..", "..", "..")))
if REPO_ROOT not in sys.path:
    sys.path.append(REPO_ROOT)

from test.unittests.testutil import open_file
from test.unittests.ner_ut.metacases import NER_FEATS_METACASES


SKIP_SCANNEDTOKENNER_TESTS = False    # useful when generating Java tests as ScannedTokenNER is Python-only
NON_STATIC_CLASSES = ('ScannedTokenNER',)
DEFAULT_FILENAMES = {
    'java': './TestLT3Feats.java',
    'python': './feat_test_autogen.py',
}
MY_NAME = __file__.split(os.sep)[-1]
TIME_NOW = '{0:%Y-%m-%d %H:%M:%S}'.format(datetime.now())
SKIP_REASON_MARKER = "R:"   # arguments starting with this are actually reasons to skip the test
DOT = "."


py_formatter = {
    "header": """\
# coding: utf-8
# !! AUTO-GENERATED by {} on {} !!
# !! DO NOT EDIT - YOUR CHANGES MAY BE OVERWRITTEN !!

import unittest

import ner_steps.feat_vect as feat_vect
from ner_steps.feat_vect import ScannedTokenNER\n""".format(MY_NAME, TIME_NOW),

    "class_open": "class {}(unittest.TestCase):",
    "skip_decorate" : "@unittest.skip({!r})",
    "func_declare": "def",
    "func_args": "(self)",
    "func_open": ":",
    "func_close" : "",
    "assertEqual": 'self.assertEqual',
    "assertTrue": 'self.assertTrue',
    "assertFalse": 'self.assertFalse',
    "comment": "#",
    "end_stmt": "",
    "footer": "\n\nif __name__ == '__main__':\n    unittest.main()",
}

java_formatter = {
    "header": """\
/* !! AUTO-GENERATED by {} on {} !!
 * !! DO NOT EDIT - YOUR CHANGES MAY BE OVERWRITTEN !!
 */

package feats;

import static org.junit.Assert.assertEquals;
import org.junit.runner.RunWith;
import org.junit.experimental.runners.Enclosed;
import org.junit.Test;
import org.junit.Ignore;\n""".format(MY_NAME, TIME_NOW),

    "class_open": "\n@RunWith(Enclosed.class)\npublic class {} {{\n\n    public static class TheTest {{",
    "skip_decorate" : "@Ignore // {}",
    "func_declare": "@Test\n    public void",
    "func_args": "()",
    "func_open": " {",
    "func_close" : "    }\n",
    "assertEqual": "assertEquals",
    "assertTrue": 'assertTrue',
    "assertFalse": 'assertFalse',
    "comment": "//",
    "end_stmt": ";",
    "footer": """\n    }
}""",
}


class TestGenerator(object):
    """Encapsulates the unit test generation functionality."""

    def __init__(self, language, metacases, formatter, outf):
        self.language = language
        self.metacases = metacases
        self.formatter = formatter
        self.outf = open_file(outf, 'w', encoding='utf-8')

    def repr_args(self, args):
        args_list = list()
        for arg in args:
            if isinstance(arg, str):
                args_list.append('"{}"'.format(arg))
            elif isinstance(arg, (int, float)):
                args_list.append('{}'.format(arg))
            else:
                raise TypeError("Unsupported argument type: {!r}".format(type(arg)))
        return ", ".join(args_list)

    def _is_dynamic(self, classname):
        for dynamic in NON_STATIC_CLASSES:
            is_dynamic = (dynamic in classname)
            if is_dynamic:
                return True
        return False

    def generate_func(self, func_spec, cases):
        count = 0
        for case in cases:
            count += 1
            is_property = True
            func_spec_temp = func_spec
            if func_spec.endswith('()'):
                is_property = False
                func_spec_temp = func_spec.rstrip('()')
            classname, funcname = func_spec_temp.split(DOT)
            test_func_name = 'test_{}_case_{}'.format(func_spec_temp.replace(DOT, "_"), count)

            skip_reason = None
            args = case[1]
            if isinstance(case[1][-1], str) and case[1][-1].startswith(SKIP_REASON_MARKER):
                skip_reason = case[1][-1]
                args = case[1][:-1]

            if skip_reason:
                print("\n    {}".format(self.formatter["skip_decorate"].format(skip_reason[2:])), file=self.outf)
            else:
                print("", file=self.outf)
            print("    {} {}{}{}".format(self.formatter['func_declare'], test_func_name, self.formatter['func_args'], self.formatter['func_open']), file=self.outf)

            is_dynamic = self._is_dynamic(classname)
            func_args = args[1:] if is_dynamic else args
            assert not (is_property and func_args), 'Property function {!r} given with arguments {!r}'.format(funcname, func_args)

            normal_call = "{}.{}({})".format(classname, funcname, self.repr_args(func_args))
            if func_args:
                special_call = '{}("{}").{}({})'.format(classname, args[0], funcname, self.repr_args(args[1:]))
            elif is_property:
                special_call = '{}("{}").{}'.format(classname, args[0], funcname)
            else:
                special_call = '{}("{}").{}()'.format(classname, args[0], funcname)

            if case[0][0] == 'assertEqual' and is_dynamic:
                assert_method = case[0][0]
                expected_value = case[0][1].rstrip()
                if assert_method == 'assertEqual' and expected_value in ("0", "1"):
                    assert_method = 'assertTrue' if expected_value == "1" else 'assertFalse'
                    print('        {}({}){}'.format(self.formatter[assert_method], special_call, self.formatter['end_stmt']), file=self.outf)
                else:
                    print('        {}("{}", {}){}'.format(self.formatter[assert_method], expected_value, special_call, self.formatter['end_stmt']), file=self.outf)
            elif case[0][0] == 'assertEqual' and not is_dynamic:
                print('        {}("{}", {}){}'.format(self.formatter[case[0][0]], case[0][1], normal_call, self.formatter['end_stmt']), file=self.outf)
            elif case[0][0] in ('assertTrue', 'assertFalse') and is_dynamic:
                print('        {}({}){}'.format(self.formatter[case[0][0]], special_call, self.formatter['end_stmt']), file=self.outf)
            elif case[0][0] in ('assertTrue', 'assertFalse') and not is_dynamic:
                print('        {}({}){}'.format(self.formatter[case[0][0]], normal_call, self.formatter['end_stmt']), file=self.outf)

            else:
                raise TypeError("Unexpected case received: {!r}; {!r}".format(case[0], case))
            print(self.formatter["func_close"], end="", file=self.outf)

    def generate_all(self):
        test_class_name = 'Test' + list(self.metacases.keys())[0][0].split('.')[0]
        print(self.formatter['header'], file=self.outf)
        print (self.formatter['class_open'].format(test_class_name), file=self.outf)
        for func_specs, cases in self.metacases.items():
            for func_spec in func_specs:
                classname = func_spec.split(DOT)[0]
                is_dynamic = self._is_dynamic(classname)
                if self.language == 'java' and is_dynamic:
                    continue

                print("\n    {} {}".format(self.formatter['comment'], ('_' * 72)), file=self.outf)
                print("    {} Test cases for function {}".format(self.formatter['comment'], func_spec), file=self.outf)
                assert DOT in func_spec, "we expect a class plus a func name, dot-separated; got {!r}".format(func_spec)
                self.generate_func(func_spec, cases)
        print(self.formatter["footer"], file=self.outf)


def main(argv):
    import argparse
    parser= argparse.ArgumentParser()
    parser.add_argument("-l", "--language", required=True, choices=['java', 'python'],
                         help="the programming language to generate the output in (required)")
    parser.add_argument('-o', '--outfile', default=None, help="Output filename ('-' for stdout; default: one of {!r})"
                                                               .format(", ".join(DEFAULT_FILENAMES.values())))
    args =  parser.parse_args(argv)
    args.outfile = sys.stdout if args.outfile in ('-', '--') else args.outfile
    args.outfile = args.outfile if args.outfile else DEFAULT_FILENAMES[args.language]
    print("Writing", args.language, "tests to output file", args.outfile, "...", file=sys.stderr)
    formatter = java_formatter if args.language == 'java' else py_formatter
    TestGenerator(args.language, NER_FEATS_METACASES, formatter, args.outfile).generate_all()


if __name__ == '__main__':
    main(sys.argv[1:])
    print("Generation DONE.", file=sys.stderr)
