from lets.abstract_step import DualInputStep
from itertools import takewhile
import argparse


class MakeLemmaOutputDEF(DualInputStep):
    def __init__(self, l):
        super().__init__(l)
        self.language = l
        self.to_checks = {
            'en': ['JJR', 'JJS', 'MD', 'NNS', 'PRP', 'RB', 'RBR', 'RBS', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ'],
            'fr': ['FtW', 'VER:pres', 'ADJ', 'NOM', 'VER:simp', 'VER:impf', 'VER:ppre', 'VER:subi', 'VER:impe',
                   'VER:subp', 'VER:futu', 'VER:cond', 'VER:pper'],
            'nl': ['WW(vd,met-e)', 'N(mv)', 'ADJ(sup,zonder)', 'N(ev,dim)', 'WW(pv,verl,mv)', 'ADJ(sup,met-e,stan)',
                   'WW(vd,zonder)', 'WW(pv,tgw,met-t)', \
                   'WW(pv,tgw,ev)', 'ADJ(comp,zonder)', 'N(mv,dim)', 'ADJ(basis,met-e,stan)', 'WW(pv,verl,ev)',
                   'WW(od,zonder)', 'ADJ(comp,met-e,stan)', 'N(ev,dat)', \
                   'WW(od,met-e)', 'VNW(onbep)', 'VNW(bez)', 'NUM(rang)', 'NUM(hoofd,mv-n,dim)', 'VNW(pers)',
                   'N(ev,gen)', 'NUM(rang,mv-n)', 'ADJ(basis,met-e,mv-n)', \
                   'LID()', 'VNW(recip)', 'ADJ(basis,met-s)', 'VNW(vb)', 'WW(pv,conj,ev)', 'ADJ(basis,met-e,bijz)',
                   'VNW(aanw)', 'WW(inf,met-e)', 'WW(pv,verl,met-t)', \
                   'NUM(hoofd,dim)', 'WW(vd,met-e,mv-n)', 'ADJ(dim)', 'NUM(hoofd,mv-n)', 'WW(od,met-e,mv-n)',
                   'NUM(hoofd,bijz)', 'ADJ(sup,met-e,mv-n)', 'ADJ(comp,met-e,mv-n)', \
                   'VNW(betr)', 'ADJ(comp,met-e,bijz)', 'ADJ(basis,zonder,mv-n)', 'VZ(versm)', 'NUM(rang,bijz)',
                   'ADJ(comp,met-s)', 'N(ev,dim,gen)', 'ADJ(sup,met-e,bijz)'],
            'de': ['ADJ', 'APPRART', 'ART', 'CARD', 'NN', 'NE', 'PIAT', 'PIS', 'PD', 'PPOSAT', 'PPOSS', 'PPER',
                   'PRF',
                   'PRELAT', 'PRELS', \
                   'PWAT', 'VFIN', 'VMFIN', 'VIMP', 'VPP']
        }
        self.to_check = self.to_checks[l]
        lemma_funs = {'en': self.getLemma1, 'fr': self.getLemma1, 'nl': self.get_lemma_nl, 'de': self.get_lemma_de}
        self.lemma_fun = lemma_funs[l]
        self.first_empty_line = True

    def process_dual_lines(self, lines, lemmas1s, lemmas2s):
        for line in lines:
            if line.strip():
                lemmas1 = takewhile(lambda l: l.strip() != '', lemmas1s)
                if self.language in ['de', 'nl']:
                    lemmas2 = takewhile(lambda l: l.strip() != '', lemmas2s)
                else:
                    lemmas2 = None
                self.first_empty_line = True
                for l in self.process_line(line, lemmas1, lemmas2):
                    yield l
            else:
                if not self.first_empty_line:
                    yield ''
                self.first_empty_line = False

    def process_line(self, line, lemmas1, lemmas2):
        items = line.strip().split()
        # MVDK 12-05-2015: changes have been made to the following 3 lines because the format of the file containing the words with adjusted capitalization has changed (it now contains the original word form in the first column and the word form with adjusted capitalization in the second column, instead of the latter in the first column)
        orgWord = items[0]
        word = items[1]
        POS = items[2]
        # get the corresponding lemmatag and its probability generated by the CRF++ model
        lemProb = next(lemma.strip().split()[-1] for lemma in lemmas1 if len(lemma.strip().split()) > 2)
        next(lemmas1, None)
        lemmaTag = lemProb[:lemProb.rfind('/')]

        lemma, probability = self.lemma_fun(word, POS, lemmaTag, self.to_check, lemProb, lemmas2)
        if POS not in self.to_check:
            probability = '/'
        # deduce the actual lemma # MVDK 12-05-2015: also write out the original word form
        output = orgWord + ' ' + lemma
        output += ' ' + probability  # also add the probability of the lemma to the output
        output.encode('utf8')
        yield output

    def get_lemma_de(self, word, POS, lemmaTag, toCheck, lemProb, lemmas2):
        probability = lemProb[lemProb.rfind('/') + 1:]
        lemma, _ = self.getLemma1(word, POS, lemmaTag, toCheck, self.language, lemmas2)
        # in the case of past participles (VPP) and infinitives with zu (VIZU), it's possible a prefix or infix ('ge(g)' or 'zu' resp.) needs to be deleted from the word - for this the output of the 2nd CRF++ lemmatization model is needed

        # the lemma tag and its probability generated by the 2nd CRF++ lemmatization model
        lemProb2 = next(lemma.strip().split()[-1] for lemma in lemmas2 if len(lemma.strip().split()) > 2)
        next(lemmas2, None)
        lemmaTag2 = lemProb2[:lemProb2.rfind('/')]
        probability2 = lemProb2[lemProb2.rfind('/') + 1:]

        if POS == 'VPP':
            probability = str(round(float(probability) * float(probability2),
                                    12))  # the probability of the actual lemma is the product of the probabilities calculated by the two CRF++ models
            if 'ge' in lemmaTag2:
                cutPart = lemmaTag2[lemmaTag2.find('g'):]  # prefix/infix that needs to be deleted
                cutPos = int(lemmaTag2[:lemmaTag2.find(
                    'g')])  # position of the word where the prefix/infix needs to be deleted
                if lemma[cutPos:].startswith(cutPart):
                    if cutPos == 0:
                        lemma = lemma[len(cutPart):]
                    else:
                        lemma = lemma[:cutPos] + lemma[cutPos + len(cutPart):]
        if POS == 'VIZU':
            # the lemma tag and its probability generated by the 2nd CRF++ lemmatization model is needed
            probability = str(float(probability) * float(
                probability2))  # the probability of the actual lemma is the average of the probabilities calculated by the two CRF++ models
            if 'zu' in lemmaTag2:
                cutPart = lemmaTag2[lemmaTag2.find('z'):]  # infix that needs to be deleted
                cutPos = int(
                    lemmaTag2[
                    :lemmaTag2.find('z')])  # position of the word where the infix needs to be deleted
                if lemma[cutPos:].startswith(cutPart):
                    if cutPos == 0:
                        lemma = lemma[len(cutPart):]
                    else:
                        lemma = lemma[:cutPos] + lemma[cutPos + len(cutPart):]
        return lemma, probability

    def get_lemma_nl(self, word, POS, lemmaTag, toCheck, lemProb, lemmas2):
        probability = lemProb[lemProb.rfind('/') + 1:]
        lemma, _ = self.getLemma1(word, POS, lemmaTag, toCheck, lemProb, lemmas2)  # deduce the actual lemma
        lemProb2 = next(lemma.strip().split()[-1] for lemma in lemmas2 if len(lemma.strip().split()) > 2)
        next(lemmas2, None)
        # in the case of past participles, it's possible a prefix or infix ('ge' or 'geg') needs to be deleted from the word - for this the output of the 2nd CRF++ lemmatization model is needed
        if POS.startswith('WW(vd'):
            # lemProb2 = lemmaTags2[
            #     numberOfWords - 1]  # the lemma tag and its probability generated by the 2nd CRF++ lemmatization model
            lemmaTag2 = lemProb2[:lemProb2.rfind('/')]
            probability2 = lemProb2[lemProb2.rfind('/') + 1:]
            probability = str(round(float(probability) * float(probability2),
                                    12))  # the probability of the actual lemma is the product of the probabilities calculated by the two CRF++ models
            if lemmaTag2 != '/':
                cutPart = lemmaTag2[lemmaTag2.find('g'):]  # prefix/infix that needs to be deleted
                cutPos = int(lemmaTag2[:lemmaTag2.find(
                    'g')])  # position of the word where the prefix/infix needs to be deleted
                if lemma[cutPos:].startswith(cutPart) and len(lemma[cutPos:]) > len(cutPart): # don't proceed if nothing remains (e.g. "ge")
                    if cutPos == 0:  # a prefix needs to be deleted (i.e. at the beginning of the word)
                        lemma = lemma[len(cutPart):]  # delete prefix
                        # delete diaeresis following the deleted prefix (no longer necessary at the beginning of the word)
                        if lemma[0] == 'ä':
                            lemma = 'a' + lemma[1:]
                        elif lemma[0] == 'ë':
                            lemma = 'e' + lemma[1:]
                        elif lemma[0] == 'ï':
                            lemma = 'i' + lemma[1:]
                        elif lemma[0] == 'ö':
                            lemma = 'o' + lemma[1:]
                        elif lemma[0] == 'ü':
                            lemma = 'u' + lemma[1:]
                        else:
                            pass
                    else:  # an infix needs to be deleted (i.e. in the middle of the word)
                        lemmaA = lemma[:cutPos]  # part of the word before the infix
                        lemmaB = lemma[cutPos + len(cutPart):]  # part of the word following the infix
                        # delete diaeresis following the deleted infix
                        if lemmaB[0] == 'ä':
                            lemmaB = 'a' + lemmaB[1:]
                        elif lemmaB[0] == 'ë':
                            lemmaB = 'e' + lemmaB[1:]
                        elif lemmaB[0] == 'ï':
                            lemmaB = 'i' + lemmaB[1:]
                        elif lemmaB[0] == 'ö':
                            lemmaB = 'o' + lemmaB[1:]
                        elif lemmaB[0] == 'ü':
                            lemmaB = 'u' + lemmaB[1:]
                        else:
                            lemmaB = lemmaB
                        # if adding together the part of the word before the infix and the part of the word following the infix results in an illegal combination of vowels, a hyphen is inserted
                        if lemmaA.endswith('a'):
                            if lemmaB.startswith('a') or lemmaB.startswith('e') or lemmaB.startswith(
                                    'i') or lemmaB.startswith('u'):
                                lemma = lemmaA + '-' + lemmaB
                            else:
                                lemma = lemmaA + lemmaB
                        elif lemmaA.endswith('e'):
                            if lemmaB.startswith('e') or lemmaB.startswith('i') or lemmaB.startswith('u'):
                                lemma = lemmaA + '-' + lemmaB
                            else:
                                lemma = lemmaA + lemmaB
                        elif lemmaA.endswith('i'):
                            if lemmaB.startswith('e') or lemmaB.startswith('i') or lemmaB.startswith('j'):
                                lemma = lemmaA + '-' + lemmaB
                            else:
                                lemma = lemmaA + lemmaB
                        elif lemmaA.endswith('o'):
                            if lemmaB.startswith('e') or lemmaB.startswith('i') or lemmaB.startswith(
                                    'o') or lemmaB.startswith('u'):
                                lemma = lemmaA + '-' + lemmaB
                            else:
                                lemma = lemmaA + lemmaB
                        elif lemmaA.endswith('u'):
                            if lemmaB.startswith('i') or lemmaB.startswith('u'):
                                lemma = lemmaA + '-' + lemmaB
                            else:
                                lemma = lemmaA + lemmaB
                        else:
                            lemma = lemmaA + lemmaB
        return lemma, probability

    def getLemma1(self, word, POS, lemmaTag, toCheck, lemProb, lemmas2):
        language = self.language
        # from the lemmatag (e.g. +Den) generated by the CRF++ model we deduce the actual lemma of a word (e.g. delete the suffix 'en' at the end of the word)
        # the POS tags in the toCheck array are POS tags for which the lemma does not always equal the word (i.e. for other POS tags, no lemma output tag is needed)
        lemma = word
        if lemmaTag != '/' and POS in toCheck:
            # determine what needs to be added or deleted at the end of a word
            delTag = ''  # = suffix that needs to be deleted from the end of the word (after '+D' in the lemma tag)
            insTag = ''  # = suffix that needs to be added to the end of the word (after '+I' in the lemma tag)
            if lemmaTag.startswith('+D'):
                delTag = lemmaTag[2:]
                if '+I' in delTag:
                    delTag = delTag[:delTag.find('+I')]
                    lemmaTag = lemmaTag[lemmaTag.find('+I'):]
            if lemmaTag.startswith('+I'):
                insTag = lemmaTag[2:]
            # add and delete the determined suffixes if possible (if it's not possible, also try by lowercasing the word first)
            if delTag:
                if lemma.endswith(delTag):
                    lemma = lemma[:lemma.rfind(delTag)]
                    if insTag:
                        lemma += insTag
                else:
                    lemmaLower = lemma.lower()
                    delTagLower = delTag.lower()
                    if lemmaLower.endswith(delTagLower):
                        lemma = lemma[:-len(delTag)]
                        if insTag:
                            lemma += insTag
            elif insTag:
                lemma += insTag
        if lemma == '':
            lemma = word
        if language == 'en':
            if POS == 'VB' and word == "'ve":
                lemma = 'have'
        if language == 'fr':
            if POS == 'KON' and word == "s'":
                lemma = 'si'
        probability = lemProb[lemProb.rfind('/') + 1:]
        return lemma, probability

    def process_file(self, f_in, f_l1, f_l2, f_out):
        for l in self.process_lines(f_in, f_l1, f_l2):
            f_out.write(l + '\n')

    def process_file_by_name(self, f_in_name, f_l1_name, f_l2_name, f_out_name):
        self.process_file(open(f_in_name, 'r'), open(f_l1_name, 'r'), open(f_l2_name, 'r'), open(f_out_name, 'w'))

    @classmethod
    def main(cls):
        parser = argparse.ArgumentParser(description=cls.__name__)
        parser.add_argument("l", help="language", choices=["de", "en", "fr", "nl"])
        parser.add_argument('i', help="input file name", type=argparse.FileType('r'))
        parser.add_argument('l1', help="lemmas1 input file name", type=argparse.FileType('r'))
        parser.add_argument('-l2', help="lemmas2 input file name", type=argparse.FileType('r'))
        parser.add_argument('o', help="output file name", type=argparse.FileType('w'))

        args = parser.parse_args()
        i = args.i
        l1 = args.l1
        l2 = args.l2
        o = args.o
        optional_args = vars(args)
        del optional_args['i']
        del optional_args['l1']
        del optional_args['l2']
        del optional_args['o']
        cls(**optional_args).process_file(i, l1, l2, o)


if __name__ == "__main__":
    MakeLemmaOutputDEF.main()
