"""
POS maps definitions.

TODO: rewrite into idiomatic Python with Python dictionaries.
"""

from lets.chunker_steps.jcompat import HashMap


__all__ = ('fill_pos_maps_english', 'fill_pos_maps_french', 'fill_pos_maps_german')


def fill_pos_maps_english():
    """Creates the English-specific POS map."""
    pos_map_en = HashMap()
    pos_map_en.put("SENT", "PCT")
    pos_map_en.put("\"", "PCT")
    pos_map_en.put("''", "PCT")
    pos_map_en.put("``", "PCT")
    pos_map_en.put("(", "PCT")
    pos_map_en.put(")", "PCT")
    pos_map_en.put(",", "PCT")
    pos_map_en.put("--", "PCT")
    pos_map_en.put(":", "PCT")
    pos_map_en.put(".", "PCT")
    pos_map_en.put("CC", "CONJ-coord")
    # IN -> CONJ-subord ( na regels)
    pos_map_en.put("CD", "NUM")
    pos_map_en.put("DT", "DET")
    pos_map_en.put("EX", "EX")
    pos_map_en.put("FW", "FW")
    pos_map_en.put("IN", "PREP")
    pos_map_en.put("JJ", "ADJ")
    pos_map_en.put("JJR", "ADJ")
    pos_map_en.put("JJS", "ADJ")
    pos_map_en.put("LS", "PCT")
    pos_map_en.put("MD", "V-fin")   # OK?
    pos_map_en.put("NN", "N")
    pos_map_en.put("NNS", "N")
    pos_map_en.put("NP", "N")
    pos_map_en.put("NPS", "N")
    pos_map_en.put("PDT", "PDT")
    # posMap.put("POS",""); // -> handled by rules
    pos_map_en.put("PP", "PRON-per")
    pos_map_en.put("PP$", "PRON-pos")
    pos_map_en.put("WDT", "PRON-rel")
    pos_map_en.put("WP", "PRON-int")
    pos_map_en.put("WP$", "PRON")
    pos_map_en.put("RB", "ADV")
    pos_map_en.put("RBR", "ADV")
    pos_map_en.put("RBS", "ADV")
    pos_map_en.put("RP", "PRT")
    pos_map_en.put("SYM", "SYM")
    pos_map_en.put("TO", "PREP")
    pos_map_en.put("UH", "INT")
    pos_map_en.put("VB", "V-inf")
    pos_map_en.put("VBD", "V-fin")
    pos_map_en.put("VBG", "V-prpa")
    pos_map_en.put("VBN", "V-papa")
    pos_map_en.put("VBP", "V-fin")
    pos_map_en.put("VBZ", "V-fin")
    # pos_map_en.put("VH", "V-inf")
    # pos_map_en.put("VHD", "V-fin")
    # pos_map_en.put("VHG", "V-prpa")
    # pos_map_en.put("VHN", "V-papa")
    # pos_map_en.put("VHP", "V-fin")
    # pos_map_en.put("VHZ", "V-fin")
    pos_map_en.put("WRB", "ADV")
    # pos_map_en.put("IN/that","PRON-rel")
    return pos_map_en


def fill_pos_maps_french():
    """Creates the French-specific POS map."""
    posMapFr = HashMap()
    posMapFr.put("SENT", "PCT")
    posMapFr.put("ABR", "N")
    posMapFr.put("ABK", "N")
    posMapFr.put("ADJ", "ADJ")
    posMapFr.put("ADV", "ADV")
    posMapFr.put("DET:ART", "DET")
    posMapFr.put("DET:POS", "DET")
    posMapFr.put("INT", "INT")
    posMapFr.put("KON", "CONJ")
    posMapFr.put("NAM", "N")
    posMapFr.put("NOM", "N")
    posMapFr.put("NUM", "NUM")
    posMapFr.put("PRO", "PRON")
    posMapFr.put("PRO:DEM", "PRON-dem")
    posMapFr.put("PRO:IND", "PRON-ind")
    posMapFr.put("PRO:PER", "PRON-per")
    posMapFr.put("PRO:POS", "PRON-pos")
    posMapFr.put("PRO:REL", "PRON-rel")
    posMapFr.put("PRP", "PREP")
    posMapFr.put("PRP:det", "PREP-det")
    posMapFr.put("PUN", "PCT")
    posMapFr.put("PUN:cit", "PCT")
    posMapFr.put("SENT", "PCT")
    posMapFr.put("SYM", "SYM")
    posMapFr.put("VER:cond", "V-fin")
    posMapFr.put("VER:futu", "V-fin")
    posMapFr.put("VER:impe", "V-fin")
    posMapFr.put("VER:impf", "V-fin")
    posMapFr.put("VER:pres", "V-fin")
    posMapFr.put("VER:simp", "V-fin")
    posMapFr.put("VER:subi", "V-fin")
    posMapFr.put("VER:subp", "V-fin")
    posMapFr.put("VER:infi", "V-inf")
    posMapFr.put("VER:ppre", "V-prpa")
    posMapFr.put("VER:pper", "V-papa")
    return posMapFr


def fill_pos_maps_german():
    """Creates the German-specific POS map."""
    posMapDe = HashMap()
    posMapDe.put("ADJA", "ADJ")
    posMapDe.put("ADJD", "ADV")
    posMapDe.put("ADV", "ADV")
    posMapDe.put("APPR", "PREP")
    posMapDe.put("APPRART", "PREP-det")
    posMapDe.put("APPO", "PREP")
    posMapDe.put("APZR", "PREP")
    posMapDe.put("ART", "DET")
    posMapDe.put("CARD", "NUM")
    # foreign language, code ok?
    posMapDe.put("FM", "N")
    posMapDe.put("ITJ", "INT")
    posMapDe.put("KON", "CONJ-coord")
    posMapDe.put("KOUI", "CONJ-subord")
    posMapDe.put("KOUS", "CONJ-subord")
    # ok? als, wie (fr: comme)
    posMapDe.put("KOKOM", "CONJ")
    posMapDe.put("NN", "N")
    posMapDe.put("NE", "N")
    posMapDe.put("PDS", "PRON-dem")
    posMapDe.put("PDAT", "PRON-dem")
    posMapDe.put("PIS", "PRON-ind")
    posMapDe.put("PIAT", "PRON-ind")
    posMapDe.put("PIDAT", "PRON-ind")
    # ok? irreflexive (ich, er, ihm, mich, dir)
    posMapDe.put("PPER", "PRON-per")
    posMapDe.put("PRF", "PRON-per")
    posMapDe.put("PPOSS", "PRON-pos")
    posMapDe.put("PPOSAT", "PRON-pos")
    posMapDe.put("PRELS", "PRON-rel")
    posMapDe.put("PRELAT", "PRON-rel")
    posMapDe.put("PWS", "PRON-int")
    # welche, wessen (adj?)
    posMapDe.put("PWAT", "PRON-int")
    # warum, wo, wann (adv?)
    posMapDe.put("PWAV", "PRON-int")
    posMapDe.put("PAV", "ADV")
    posMapDe.put("PTKZU", "PREP")
    posMapDe.put("PTKNEG", "ADV")
    posMapDe.put("PTKVZ", "PREP")
    posMapDe.put("PTKANT", "ADV")
    posMapDe.put("PTKA", "PREP")
    # An- und abreise
    posMapDe.put("TRUNC", "PREP")
    posMapDe.put("VVFIN", "V-fin")
    posMapDe.put("VVIMP", "V-fin")
    posMapDe.put("VVINF", "V-inf")
    posMapDe.put("VVIZU", "V-inf")
    posMapDe.put("VVPP", "V-papa")
    posMapDe.put("VAFIN", "V-fin")
    posMapDe.put("VAIMP", "V-fin")
    posMapDe.put("VAINF", "V-inf")
    posMapDe.put("VAPP", "V-papa")
    posMapDe.put("VMFIN", "V-fin")
    posMapDe.put("VMINF", "V-inf")
    posMapDe.put("VMPP", "V-papa")
    # nicthwort: D2XW3
    posMapDe.put("XY", "N")
    posMapDe.put("$,", "PCT")
    posMapDe.put("$.", "PCT")
    posMapDe.put("$(", "PCT")
    return posMapDe
